/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "substring.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static char **
_generaterandomstring_1 (int  *argp, struct svc_req *rqstp)
{
	return (generaterandomstring_1_svc(*argp, rqstp));
}

static bool_t *
_containsforbiddensubstr_1 (containsforbiddensubstr_1_argument *argp, struct svc_req *rqstp)
{
	return (containsforbiddensubstr_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, rqstp));
}

static void
substring_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int generaterandomstring_1_arg;
		containsforbiddensubstr_1_argument containsforbiddensubstr_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case generaterandomstring:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _generaterandomstring_1;
		break;

	case containsforbiddensubstr:
		_xdr_argument = (xdrproc_t) xdr_containsforbiddensubstr_1_argument;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) _containsforbiddensubstr_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SUBSTRING, V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SUBSTRING, V1, substring_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUBSTRING, V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SUBSTRING, V1, substring_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUBSTRING, V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
