/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MULTIPLY_H_RPCGEN
#define _MULTIPLY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct multiply_1_argument {
	int arg1;
	int arg2;
};
typedef struct multiply_1_argument multiply_1_argument;

#define RPCDJAMEL 0x12345678
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLY 1
extern  int * multiply_1(int , int , CLIENT *);
extern  int * multiply_1_svc(int , int , struct svc_req *);
extern int rpcdjamel_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLY 1
extern  int * multiply_1();
extern  int * multiply_1_svc();
extern int rpcdjamel_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_multiply_1_argument (XDR *, multiply_1_argument*);

#else /* K&R C */
extern bool_t xdr_multiply_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MULTIPLY_H_RPCGEN */
