/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "substring.h"

bool_t
xdr_is_forbidden_substring_1_argument (XDR *xdrs, is_forbidden_substring_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg4, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_generate_next_char_1_argument (XDR *xdrs, generate_next_char_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg4, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_generate_string_without_substrings_1_argument (XDR *xdrs, generate_string_without_substrings_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg4, ~0))
		 return FALSE;
	return TRUE;
}
