/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUBSTRING_H_RPCGEN
#define _SUBSTRING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct is_forbidden_substring_1_argument {
	char *arg1;
	char **arg2;
};
typedef struct is_forbidden_substring_1_argument is_forbidden_substring_1_argument;

struct generate_next_char_1_argument {
	char *arg1;
	int arg2;
	char **arg3;
};
typedef struct generate_next_char_1_argument generate_next_char_1_argument;

struct generate_string_without_substrings_1_argument {
	int arg1;
	char **arg2;
	char *arg3;
};
typedef struct generate_string_without_substrings_1_argument generate_string_without_substrings_1_argument;

#define SUBSTRING 0x12345678
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define is_forbidden_substring 1
extern  int * is_forbidden_substring_1(char *, char **, CLIENT *);
extern  int * is_forbidden_substring_1_svc(char *, char **, struct svc_req *);
#define generate_next_char 2
extern  char * generate_next_char_1(char *, int , char **, CLIENT *);
extern  char * generate_next_char_1_svc(char *, int , char **, struct svc_req *);
#define generate_string_without_substrings 3
extern  void * generate_string_without_substrings_1(int , char **, char *, CLIENT *);
extern  void * generate_string_without_substrings_1_svc(int , char** , char *, struct svc_req *);
extern int substring_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define is_forbidden_substring 1
extern  int * is_forbidden_substring_1();
extern  int * is_forbidden_substring_1_svc();
#define generate_next_char 2
extern  char * generate_next_char_1();
extern  char * generate_next_char_1_svc();
#define generate_string_without_substrings 3
extern  void * generate_string_without_substrings_1();
extern  void * generate_string_without_substrings_1_svc();
extern int substring_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_is_forbidden_substring_1_argument (XDR *, is_forbidden_substring_1_argument*);
extern  bool_t xdr_generate_next_char_1_argument (XDR *, generate_next_char_1_argument*);
extern  bool_t xdr_generate_string_without_substrings_1_argument (XDR *, generate_string_without_substrings_1_argument*);

#else /* K&R C */
extern bool_t xdr_is_forbidden_substring_1_argument ();
extern bool_t xdr_generate_next_char_1_argument ();
extern bool_t xdr_generate_string_without_substrings_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUBSTRING_H_RPCGEN */
